### ISSUE TITLE
Keep raising the density threshold until tiles are small enough

### ISSUE THREAD

**Issue by ericfischer** [mapbox/tile-count#34]
Some tiles are coming out larger than 500K.

**Comment by aaronlidman** [comment]
Great idea, would this be global or per zoom level?

**Comment by ericfischer** [comment]
Per zoom level would probably be good enough. Per tile is actually what I was thinking but it might look bad.

Either global or per zoom level means having to make another pass through the whole thing if it needs to raise the limit, unfortunately, while per-tile would be self-contained.

**Comment by mtirwin** [comment]
@ericfischer is this something we can work around manually in the meantime by increasing the `maxZoom` param in telemetry-density-map, or unrelated?

**Comment by ericfischer** [comment]
@mtirwin Yes, if you raise the `maxZoom` and lower the `density` you will end up with the same ultimate data, one zoom higher than before, with each tile being smaller.

**Comment by ericfischer** [comment]
Added `-K` option in https://github.com/mapbox/tile-count/pull/35.

This only ended up affecting a single tile in the global tileset ([5/8/12](http://a.tile.openstreetmap.org/5/8/12.png)).
